import { Box } from '@mui/material';
import type { Metadata } from 'next';
import '../styles/global.scss';
import AppProvider from './provide';
import Header from '@/components/Header';

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

const RootLayout = ({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) => {
    return (
        <html lang="en">
            <Box component="body">
                <AppProvider>
                    <Header />
                    {children}
                </AppProvider>
            </Box>
        </html>
    );
};

export default RootLayout;
