import { Box } from '@mui/material';
import type { Metadata } from 'next';
import '../styles/global.scss';
import AppProvider from './provide';
import Header from '@/components/Header';

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

const RootLayout = ({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) => {
    return (
        <html lang="en">
            <Box component="body">
                <AppProvider>
                    <Header />
                    {children}
                </AppProvider>
            </Box>
        </html>
    );
};

export default RootLayout;

// const RootLayout: FC<AppProps> = ({ Component, pageProps }) => {
//     return (
//         <html lang="en">
//             <Box component="body">
//                 <Header />
//                 <Component {...pageProps} />
//             </Box>
//         </html>
//     );
// };

// export default appWithTranslation(RootLayout);

// import { Box } from '@mui/material';
// import type { Metadata } from 'next';
// import '../styles/global.scss';
// import Header from '@/components/Header';
// import { appWithTranslation } from 'next-i18next';
// import type { AppProps } from 'next/app';
// import { FC } from 'react';

// export const metadata: Metadata = {
//     title: 'Create Next App',
//     description: 'Generated by create next app',
// };

// const MyApp: FC<AppProps> = ({ Component, pageProps }) => {
//     return (
//         <html lang="en">
//             <Box component="body">
//                 <Header />
//                 <Component {...pageProps} />
//             </Box>
//         </html>
//     );
// };

// // export default appWithTranslation(MyApp);
// export default MyApp;
// 'use client';

// import { Box } from '@mui/material';
// import type { Metadata } from 'next';
// import '../styles/global.scss';
// import Header from '@/components/Header';
// // import { appWithTranslation } from 'next-i18next';
// import type { AppProps } from 'next/app';
// import { FC } from 'react';

// export const metadata: Metadata = {
//     title: 'Create Next App',
//     description: 'Generated by create next app',
// };

// const RootLayout: FC<AppProps> = ({ Component, pageProps }) => {
//     return (
//         <html lang="en">
//             <Box component="body">
//                 <Header />
//                 <Component {...pageProps} />
//             </Box>
//         </html>
//     );
// };
// export default RootLayout;
// export default appWithTranslation(RootLayout);
