import { Box } from '@mui/material';
import type { Metadata } from 'next';
import '../../styles/global.scss';
import Header from '@/components/Header';
import { NextIntlClientProvider } from 'next-intl';
import { getMessages } from 'next-intl/server';

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

const RootLayout = async ({
    children,
    params: { locale },
}: Readonly<{
    children: React.ReactNode;
    params: { locale: string };
}>) => {
    const messages = await getMessages();
    return (
        <html lang={locale}>
            <Box component="body">
                <NextIntlClientProvider messages={messages}>
                    <Header />
                    {children}
                </NextIntlClientProvider>
            </Box>
        </html>
    );
};

export default RootLayout;
